---
# tasks file for deploy_docker
- name: "upgrade Ubuntu"
  apt:
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: "install pkg"
  apt:
    pkg:
    - ca-certificates
    - curl
    - gnupg
    state: present
  when: ansible_distribution == "Ubuntu"

- name: "add gpt key Ubuntu"
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  when: ansible_distribution == "Ubuntu"

- name: "add repository"
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
  when: ansible_distribution == "Ubuntu"

- name: "upgrade Ubuntu"
  apt:
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: "install docker Ubuntu"
  apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose
      - docker-compose-plugin
    state: present
  when: ansible_distribution == "Ubuntu"

- name: "add user in group docker"
  user:
    name: user
    state: present
    append: yes
    groups: docker
  when: ansible_distribution == "Ubuntu"


- name: "yum update centos"
  yum:
    update_cache: yes
  when: ansible_distribution == "CentOS"

- name: "install rep CentOS"
  yum:
    name:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
    state: present
  when: ansible_distribution == "CentOS"

- name: "add rep CentOS"
  command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  when: ansible_distribution == "CentOS"

- name: "install docker CentOS"
  yum:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
  when: ansible_distribution == "CentOS"

- name: "start docker CentOS"
  systemd:
    name: docker
    state: started
    enabled: true
  when: ansible_distribution == "CentOS"

# tasks file for dockerinst

