apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  selector:
    app: mydb
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432

---
apiVersion: v1
kind: Service
metadata:
  name: app-services
spec:
  ports:
  # Порт сетевого балансировщика, на котором будут обслуживаться пользовательские запросы.
  - name: port1
    protocol: TCP
    port: 3003
    # Порт контейнера, на котором доступно приложение.
    targetPort: 3003
  # Метки селектора, использованные в шаблоне подов при создании объекта Deployment.
    nodePort: 31060
  selector:
    app: myapp
      #  externalIPs:
      #    -  158.160.117.19
  type: LoadBalancer
