apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-persistent-volume-clime
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
